# Generated by Django 4.0.6 on 2022-07-11 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=100)),
                ('StartTime', models.DateTimeField()),
                ('EndTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subquestions', models.CharField(max_length=2000)),
                ('sub', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic', to='api.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Option', models.CharField(max_length=1000)),
                ('righ', models.BooleanField(default=False)),
                ('Que', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Querry', to='api.questions')),
            ],
        ),
    ]
